FROM node:18-alpine as builder
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./src/nginx/default.conf /etc/nginx/conf.d/default.conf
ENV VITE_BASE_URL: http://aa6fa525644e14bc6a2365d099504e2c-1084886360.eu-central-1.elb.amazonaws.com/erp/api

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



