FROM node:21-alpine3.17 AS builder
WORKDIR /app
RUN npm install -D typescript
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM node:21-alpine3.17
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm install
EXPOSE 6000
CMD ["node", "./dist/server.js"]