apiVersion: v1
kind: ConfigMap
metadata:
  name: oms-server-configmap
  namespace: oms
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  JWT_SECRET: "project-team1"
  MONGODB_URI: "mongodb://root:password@my-mongodb-release-0.my-mongodb-release-headless.oms.svc.cluster.local:27017,my-mongodb-release-1.my-mongodb-release-headless.oms.svc.cluster.local:27017,my-mongodb-release-2.my-mongodb-release-headless.oms.svc.cluster.local:27017"
  POSTGRESQL_CONNECTION_STRING: "postgresql://postgres:root@my-postgress-release-postgresql.oms.svc.cluster.local:5432/users"
  PORT: "5000"
