export default {
    portMissing: 'PORT not found in environment variables',
    mongoDBURImissing: 'MONGODB_URI not found in environment variables',
    postgreSQLconStrMissing: 'POSTGRESQL_CONNECTION_STRING not found in environment variables',
    JWTkeyMissing: "JWT_SECRET not found in environment variables",
    productsURLmissing: 'ALL_PRODUCT_URL not found in environment variables',
    gmailUNmissing: 'GMAIL_USERNAME not found in environment variables',
    gmailPWmissing: 'GMAIL_APP_PASSWORD not found in environment variables',
    incorrectPassword: 'incorrect password',
    emailExist: 'email already exist',
    invalidID: 'user ID must be string of digits',
    usernameTaken: 'username already taken',
    userNotExist: 'user not exist',
    productIDNotExist: 'productID not exist',
    productNotExist: 'product not exist',
    categoryNotExist: 'category not exist',
    invalidPayload: 'invalid payload',
    invalidToken: 'invalid token',
    bannerExistForProduct: 'banner with this productID already exist'
}